### ISSUE TITLE
No module named 'kerop'

### ISSUE THREAD

**Issue by ayusdixit** [kentaroy47/keras-Opcounter#4]
![Screenshot 2023-07-10 at 18-54-04 Detection of Malaria - Jupyter Notebook](https://github.com/kentaroy47/keras-Opcounter/assets/63745645/fd776ce9-1c90-4f04-8c6a-d58f18d3a1d8)
can u suggest what i am doing wrong?

**Comment by kentaroy47** [comment]
something happened in the server side?
can you try
`pip install --upgrade --no-cache-dir --use-deprecated=legacy-resolver kerop`

https://stackoverflow.com/questions/67074684/pip-has-problems-with-metadata
